### ISSUE TITLE
impossible to connect with 2025.8.3

### ISSUE THREAD

**Issue by Kawabountou** [gduteil/cozytouch#69]
Hi,

First of all, thanks for your application that permit me to save a lot of money.

After an upgrade to 2025.8.3, it's impossible to connect to my account.

an update is shcedule or I shoud go back to the previous version?

Best regards,

**Comment by cece46** [comment]
Traceback (most recent call last):
  File "/config/custom_components/cozytouch/config_flow.py", line 51, in async_step_user
    hub = await validate_input(self.hass, user_input)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/cozytouch/config_flow.py", line 28, in validate_input
    result = await hub.test_connection()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/cozytouch/hub.py", line 97, in test_connection
    await self.connect()
  File "/config/custom_components/cozytouch/hub.py", line 166, in connect
    await self._update_localization(
        json_data[0]["address"].get("country", None)
    )
  File "/config/custom_components/cozytouch/hub.py", line 623, in _update_localization
    if localization.get("countryCode", "") == country:
       ^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
